version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: talent_register_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: talent_register
      MYSQL_USER: talent_user
      MYSQL_PASSWORD: talent_pass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - talent_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: talent_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - talent_network

volumes:
  mysql_data:
    driver: local

networks:
  talent_network:
    driver: bridge
